name: yandex_school_homework
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  provider: ^6.1.5
  dio: ^5.8.0+1
  talker_flutter:
  talker_dio_logger:
  envied: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  envied_generator: ^1.1.1
  build_runner: 2.4.15

flutter:
  uses-material-design: true
