name: yandex_school_homework
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  provider: ^6.1.5
  dio: ^5.8.0+1
  talker_flutter:
  talker_dio_logger:
  envied: ^1.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.7
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  sensors_plus: ^6.1.1
  fuzzy: ^0.5.1
  sqflite: ^2.4.2
  path: ^1.9.1 # надо для sqflite
  flutter_launcher_icons: ^0.14.4

  pie_chart_package:
    path: ./local_libs/pie_chart_package
  fl_chart: ^1.0.0
  connectivity_plus: ^6.1.4
  worker_manager: ^7.2.6
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  envied_generator: ^1.1.1
  build_runner: 2.4.15
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  flutter_gen_runner: 5.10.0
  flutter_gen: 5.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/gifs/

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"